services:
  gateway:
    build: ./gateway
    image: gateway
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
      - SERVER_PORT=8080

  server:
    build: ./server
    restart: on-failure
    container_name: server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SERVER_PORT=9090
  db:
    image: postgres:13.7-alpine
    container_name: db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=dbuser
      - POSTGRES_DB=shareit