DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS requests;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
  user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(512) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (user_id),
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS requests (
  request_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  description VARCHAR(2000),
  requestor_id BIGINT,
  CONSTRAINT pk_request PRIMARY KEY (request_id),
  CONSTRAINT fk_requestor_requests FOREIGN KEY (requestor_id) REFERENCES users
);

CREATE TABLE IF NOT EXISTS items (
  item_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(2000),
  is_available BOOLEAN,
  owner_id BIGINT,
  request_id BIGINT,
  CONSTRAINT pk_item PRIMARY KEY (item_id),
  CONSTRAINT fk_owner_items FOREIGN KEY (owner_id) REFERENCES users,
  CONSTRAINT fk_request_items FOREIGN KEY (request_id) REFERENCES requests
);

CREATE TABLE IF NOT EXISTS comments (
  comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  text VARCHAR(2000),
  item_id BIGINT,
  author_id BIGINT,
  created TIMESTAMP WITHOUT TIME ZONE,
  CONSTRAINT pk_comment PRIMARY KEY (comment_id),
  CONSTRAINT fk_item_comments FOREIGN KEY (item_id) REFERENCES items,
  CONSTRAINT fk_author_comments FOREIGN KEY (author_id) REFERENCES users
);


CREATE TABLE IF NOT EXISTS bookings (
  booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  start_date TIMESTAMP WITHOUT TIME ZONE,
  end_date TIMESTAMP WITHOUT TIME ZONE,
  item_id BIGINT,
  booker_id BIGINT,
  status VARCHAR(255),
  CONSTRAINT pk_booking PRIMARY KEY (booking_id),
  CONSTRAINT fk_item_bookings FOREIGN KEY (item_id) REFERENCES items,
  CONSTRAINT fk_booker_bookings FOREIGN KEY (booker_id) REFERENCES users
);